<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Alex+Brush" rel="stylesheet">
<link rel="stylesheet" href="./web/css/open-iconic-bootstrap.min.css"> 
<link rel="stylesheet" href="./web/css/animate.css"> 
<link rel="stylesheet" href="./web/css/owl.carousel.min.css"> 
<link rel="stylesheet" href="./web/css/owl.theme.default.min.css"> 
<link rel="stylesheet" href="./web/css/magnific-popup.css"> 
<link rel="stylesheet" href="./web/css/aos.css"> 
<link rel="stylesheet" href="./web/css/ionicons.min.css"> 
<link rel="stylesheet" href="./web/css/bootstrap-datepicker.css"> 
<link rel="stylesheet" href="./web/css/jquery.timepicker.css"> 
<link rel="stylesheet" href="./web/css/icomoon.css"> 
<link rel="stylesheet" href="./web/css/style.css"> 
<link rel="stylesheet" href="./web/css/flaticon.css"> 